// Placeholder LQIP base64 condiviso per gli hero — tono caldo neutro che
// matcha la palette Calce e Mare. Stesso pattern di HeroLaRotta.tsx.
export const HERO_BLUR =
  'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/2wCEAAkGBxAQEBAQEBAQEA8QDxAQDw8PDw8PDw8PFRUWFhURFRUYHSggGBolGxUVITEhJSkrLi4uFx8zODMtNygtLisBCgoKDg0OFRAQGi0lHR8tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf/AABEIAAoAFAMBIgACEQEDEQH/xAAVAAEBAQAAAAAAAAAAAAAAAAACAAH/xAAYEAEAAwEAAAAAAAAAAAAAAAAAAQIDEf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AzhfElQ2H/9k=';

export const HERO_SIZES =
  '(max-width: 768px) 100vw, (max-width: 1280px) 100vw, 1600px';
